<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/10/29 0029
 * Time: 上午 10:25
 */

namespace App\Http\AdminControllers;


class Resource extends Admin
{
    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }

    public function update()
    {

    }
}